---
title: "MyDas"
subtitle: "Productivity Analysis" 
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---
  

```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, 
               fig.width =5.5, 
               fig.height=6,
               fig.path  ="../tex/pg-",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE, 
               eval   =TRUE,
               cache  =TRUE,
               cache.path="/cache/productivity")
iFig=0
iTab=0
```

```{r init}
library(ggplot2)
library(reshape2)

library(plyr)
library(dplyr)

library(FLCore)
library(FLife)
library(popbio)

library(ggthemes)
library(scales)

dirMy="/home/laurence/Desktop/sea++/mydas"
dirDat=file.path(dirMy,"data")
```


```{r lhparams}
load("/home/laurence/Desktop/papers/generic/fishnets-master/data/fishbase-web/fishbase-web.RData")
data(wklife)

cmn =c("Sprat","Gurnards","Saithe","Pollock","Ling","Rays","Skates","John Dory","Turbot","Brill")
nm  =        c("Sprattus sprattus sprattus",
               "Chelidonichthys cuculus",
               "Pollachius virens","Pollachius pollachius","Molva molva",
               "Chondrichthyes","Chondrichthyes",
               "Zeus faber",
               "Scophthalmus maximus","Scophthalmus rhombus")
mydas=subset(fb,species%in%nm)

gurnards=subset(fb,family%in%"Triglidae")
skates  =subset(fb,family%in%"Rajiformes")

lh =lhPar(as(mydas[,-(1:5)],"FLPar"))
eql=lhEql(lh)
```

```{r r}
l=leslie(eql,fmult=refpts(eql)["crash","harvest"])

adply(l,3,lambda)

```
**Figure `r iFig=iFig+1; iFig`** 

