---
title: "Risk Analysis"
subtitle: "Productivity Analysis" 
author: "Laurie Kell & Alex Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, fig.width =8, 
               fig.height=6,
               fig.path  ="../tex/",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE,
               cache  =TRUE)
iFig=0
iTab=0
```

```{r init}
library(ggplot2)
library(reshape2)

library(plyr)
library(dplyr)

library(FLCore)
library(FLife)
library(popbio)

library(ggthemes)
library(scales)

dirMy ="/home/laurence/Desktop/sea++/mydas/tasks"
dirInp=file.path(dirMy,"inputs")
dirDat=file.path(dirMy,"data")
 
theme_set(theme_bw())
```


```{r lhparams}
load(file.path(dirDat,"lhpcns.RData"))
load(file.path(dirDat,"lhpmydas.RData"))
load(file.path(dirDat,"gurnards.RData"))
load(file.path(dirDat,"skates.RData"))
```

```{r lheql}
lh =lhPar(as(lhpmydas[,-(1:5)],"FLPar"))
eql=lhEql(lh)
```

```{r r}
l=leslie(eql,fmult=refpts(eql)["crash","harvest"])

adply(l,3,lambda)
```
**Figure `r iFig=iFig+1; iFig`** 

