---
title: "Task 2"
subtitle: "Economic Data" 
author: "Laurie Kell & Alex Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r dir}
dirMy ="/home/laurence/Desktop/sea++/mydas/tasks"
dirInp=file.path(dirMy,"inputs")
dirDat=file.path(dirMy,"data")
```

```{r knitr, echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, fig.width =8, 
               fig.height=6,
               fig.path  ="../tex/",
               warning=FALSE, 
               message=FALSE, 
               error  =FALSE, 
               echo   =FALSE,
               cache  =TRUE)
iFig=0
iTab=0
```

```{r init}
library(DBI)
library(RPostgreSQL)
library(dplyr)
library(plyr)
library(reshape)
library(ggplot2)
library(maptools)

options(scipen = 999)
theme_set(theme_bw())
```

```{r postgres}
drv=dbDriver("PostgreSQL") 

con=dbConnect(drv, host    ='postgresql-seascope.csffkpr9jjjn.eu-west-2.rds.amazonaws.com', 
                   dbname  ='mydasDev', 
                   port    =5432, 
                   user    ='MydasApplication', 
                   password='gmit2017!') 
```

```{r summary}
price=dbGetQuery(con,"SELECT * FROM data_faocodes")
```