---
title: "Cross test using Operating Model based on Life History"
subtitle: "VPA"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
vignette: >
  %\VignetteIndexEntry{FLife}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
github_document:
    mathjax: TRUE
tags: FLife
license: Creative Commons Attribution-ShareAlike 4.0 International Public License
---

```{r knitr_init, echo=FALSE, results="hide"}
library(knitr)
## Global options
opts_chunk$set(cache     =TRUE,
               cache.path="../cache/crosstest/bd",
               echo      =FALSE,
               eval      =TRUE,
               prompt    =FALSE,
               comment   =NA,
               message   =FALSE,
               warning   =FALSE,
               tidy      =TRUE,
               fig.height=10,
               fig.width =8,
               fig.path  ="../tex/crosstest-bd")

options(digits=3)

iFig=0
```
```{r pkgs}
library(ggplot2)
library(reshape)
library(plyr)
library(dplyr)
library(FLCore)
library(ggplotFL)

library(FLAssess)
library(FLXSA)

library(doParallel)
library(foreach)
```
```{r, dir}
dirMy="/home/laurence/Desktop/sea++/mydas/tasks/task5"
dirDat=file.path(dirMy,"data")

load(file.path(dirDat,"brill.RData"))

xsaControl=FLXSA.control(tol    =1e-09,maxit   =50, 
                         min.nse=0.3,  fse     =0.1, 
                         rage   =0,       qage    =10, 
                         shk.n  =TRUE,   shk.f   =TRUE, 
                         shk.yrs=4,    shk.ages=5, 
                         window =100,   tsrange =10, 
                         tspower=0,
                         vpa    =FALSE)

xsa=function(om,pg=10,ctrl=xsaControl){
  stk=setPlusGroup(om,pg)
  idx=FLIndex(index=stock.n(stk))
  range(idx)[c("plusgroup","startf","endf")]=c(pg,0.1,.2)
  
  xsa=stk+FLXSA(stk,idx,control=ctrl,diag.flag=FALSE)
  
  xsa}
```

```{r, xsa}
mp=xsa(om)
```

```{r}
plot(FLStocks(list("xsa"=mp,"om"=om)))
```

**Figure `r iFig=iFig+1; iFig`.** VPA


```{r, xsa-fwd}
registerDoParallel(4)

xsafwd=foreach(assYr=seq(75,40,-5), 
              .combine=list,
              .multicombine=TRUE,
              .packages=c("FLCore","FLAssess","FLXSA","FLasher","FLRP","plyr")) %dopar%{

    mp =xsa(window(om,end=assYr))
    sr =fmle(as.FLSR(mp,model="bevholt"),control=list(trace=FALSE))
    mp =fwdWindow(mp,end=assYr+10,FLBRP(mp))
          
    fwd(mp,catch=catch(om)[,assYr+0:10],sr=sr)
    }

xsafwd=as(xsafwd,"FLStocks")

save(xsafwd,file=file.path(dirDat,"brill/xsafwd.RData"),compress="xz")
```


```{r}
theme_set(theme_bw())

names(xsafwd)=seq(75,40,-5)
plot(xsafwd)+
  guides(col=guide_legend(title="Assessment\n Year"))
```

**Figure `r iFig=iFig+1; iFig`.** VPA cross test


```{r}
theme_set(theme_bw())

plot(iter(xsafwd,67))+
  guides(col=guide_legend(title="Assessment\n Year"))
  
```

**Figure `r iFig=iFig+1; iFig`.** VPA cross test


\newpage
## Session Info

```{r}
sessionInfo()
```

## Software Versions

* `r version$version.string`
* FLCore: `r packageVersion('FLCore')`
* FLife:  `r packageVersion('FLife')`
* FLRP:  `r packageVersion('FLRP')`
* **Compiled**: `r date()`

## Author information

**Laurence KELL**. laurie@kell.es

# References {#References}
